// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class Invoice
    {
        public Invoice()
        {
            Bookings = new HashSet<Booking>();
        }

        public int Id { get; set; }
        public DateTime IssueDate { get; set; }
        public string Status { get; set; }
        public double TotalAmount { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string PaymentType { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; }
    }
}