// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public partial class Location
    {
        public Location()
        {
            BookingDropOffLocations = new HashSet<Booking>();
            BookingPickUpLocations = new HashSet<Booking>();
            Cars = new HashSet<Car>();
            TransferFeeDropOffLocations = new HashSet<TransferFee>();
            TransferFeePickUpLocations = new HashSet<TransferFee>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int CountryId { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Booking> BookingDropOffLocations { get; set; }
        public virtual ICollection<Booking> BookingPickUpLocations { get; set; }
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<TransferFee> TransferFeeDropOffLocations { get; set; }
        public virtual ICollection<TransferFee> TransferFeePickUpLocations { get; set; }
    }
}