// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities;
using Domain.Persistence;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Domain.Persistence.Configurations
{
    public partial class BookingConfiguration : IEntityTypeConfiguration<Booking>
    {
        public void Configure(EntityTypeBuilder<Booking> entity)
        {
            entity.ToTable("Booking");

            entity.Property(e => e.CancellationDateTime).HasColumnType("datetime");

            entity.Property(e => e.FromDateTime).HasColumnType("datetime");

            entity.Property(e => e.ModificationDateTime).HasColumnType("datetime");

            entity.Property(e => e.ReturnDateTime).HasColumnType("datetime");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValueSql("(N'Booked')");

            entity.HasOne(d => d.Car)
                .WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CarId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Car");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Customer");

            entity.HasOne(d => d.DropOffLocation)
                .WithMany(p => p.BookingDropOffLocations)
                .HasForeignKey(d => d.DropOffLocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Location1");

            entity.HasOne(d => d.Invoice)
                .WithMany(p => p.Bookings)
                .HasForeignKey(d => d.InvoiceId)
                .HasConstraintName("FK_Booking_Invoice");

            entity.HasOne(d => d.Package)
                .WithMany(p => p.Bookings)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK_Booking_Package");

            entity.HasOne(d => d.PickUpLocation)
                .WithMany(p => p.BookingPickUpLocations)
                .HasForeignKey(d => d.PickUpLocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Booking_Location");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Booking> entity);
    }
}
