// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities;
using Domain.Persistence;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Domain.Persistence.Configurations
{
    public partial class CarConfiguration : IEntityTypeConfiguration<Car>
    {
        public void Configure(EntityTypeBuilder<Car> entity)
        {
            entity.ToTable("Car");

            entity.HasIndex(e => e.RegistrationNumber, "IX_Car_RegistrationNumber")
                .IsUnique();

            entity.Property(e => e.Make)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.Model)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.ModelYear)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.RegistrationNumber)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Category)
                .WithMany(p => p.Cars)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Car_Category");

            entity.HasOne(d => d.Location)
                .WithMany(p => p.Cars)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Car_Location");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Car> entity);
    }
}
